#!/bin/bash

echo "welcome to learn shell script"
echo "SURESH: HII GOOD MORNING RAMESH"
echo "RAMESH: HELLO VERY GOOD MORNING SURESH"
echo "SURESH: HOW ARE YOU DOING"
echo "RAMESH: I AM DOING GOOD, HOW ABOUT YOU SURESH"
echo "SURESH: I AM DOING GOOD TOO THANKS FOR ASKING"