#!/bin/bash

echo "here i am learning how to create a variable"
PERSON1=RAMESH
PERSON2=SURESH
echo "$PERSON2: HII GOOD MORNING $PERSON1"
echo "$PERSON2: HELLO VERY GOOD MORNING $PERSON1"
echo "$PERSON2: HOW ARE YOU DOING"
echo "$PERSON1: I AM DOING GOOD, HOW ABOUT YOU $PERSON2"
echo "$PERSON2: I AM DOING GOOD TOO THANKS FOR ASKING"